services:
  all-together:
    image: ubuntu
    command: bash
    stdin_open: true
    tty: true
    env_file: stack.env
  single-not-working:
    image: ubuntu
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FOO=${FOO}
